services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  init-db:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: init-db
    working_dir: /var/www/html
    restart: on-failure
    depends_on:
      - database
    entrypoint: ./entrypoint.sh
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - database
  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  database_data:

